name: export-and-branch-solution-secret
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

env:
  DEV_ENV_URL: 'https://orgbf149593.crm4.dynamics.com'
  SOLUTION_NAME: 'GitHubDeploy'

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: Install PAC CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ env.DEV_ENV_URL }}
        app-id: 'abcc514b-9408-40f5-831e-2b24f1238ac5'
        client-secret: ${{ secrets.secret }}
        tenant-id: '9971e591-556d-4b10-9494-3c7ab3a8df3e'
        
    - name: publish customizations
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: ${{ env.DEV_ENV_URL }}
        app-id: 'abcc514b-9408-40f5-831e-2b24f1238ac5'
        client-secret: ${{ secrets.secret }}
        tenant-id: '9971e591-556d-4b10-9494-3c7ab3a8df3e'
        
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ env.DEV_ENV_URL }}
        app-id: 'abcc514b-9408-40f5-831e-2b24f1238ac5'
        client-secret: ${{ secrets.secret }}
        tenant-id: '9971e591-556d-4b10-9494-3c7ab3a8df3e'
        solution-name: ${{ env.SOLUTION_NAME }}
        managed: true
        solution-output-file: out/exported/${{ env.SOLUTION_NAME }}_Managed.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: out/exported/${{ env.SOLUTION_NAME }}_Managed.zip
        solution-folder: out/solutions/${{ env.SOLUTION_NAME }}/Managed
        solution-type: 'Managed'
        overwrite-files: true


        
    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: out/solutions/${{ env.SOLUTION_NAME }}
        solution-target-folder: solutions/${{ env.SOLUTION_NAME }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
