name: release-managed-solution-to-prod

on:
  workflow_dispatch:

jobs:
  deploy-to-prod:
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch the managed solution
      uses: actions/download-artifact@v4
      with:
        name: GitHubDeploy
        path: out/release/

    - name: Import managed solution to production
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: 'https://org9b404353.crm4.dynamics.com'
        app-id: 'abcc514b-9408-40f5-831e-2b24f1238ac5'
        client-secret: ${{ secrets.secret }}
        tenant-id: '9971e591-556d-4b10-9494-3c7ab3a8df3e'
        solution-file: out/release/GitHubDeploy_managed.zip
        force-overwrite: true
        publish-changes: true
